import { NextResponse } from "next/server";
import puppeteer from "puppeteer";

export async function POST(req: Request) {
  try {
    const data = await req.json();

    const browser = await puppeteer.launch({
      headless: true,
      args: ["--no-sandbox", "--disable-setuid-sandbox"],
    });
    const page = await browser.newPage();

    const htmlContent = `
      <html>
        <head>
          <style>
            body { font-family: 'Inter', sans-serif; color: #171717; padding: 40px; }
            h1 { color: #3b82f6; font-size: 24px; border-bottom: 2px solid #e5e7eb; padding-bottom: 10px; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th, td { border: 1px solid #e5e7eb; padding: 12px; text-align: left; }
            th { background-color: #f9fafb; font-weight: 600; width: 40%; }
            .header { display: flex; justify-content: space-between; align-items: flex-end; }
            .badge { background: #10b981; color: white; padding: 4px 8px; border-radius: 4px; font-size: 12px; }
          </style>
        </head>
        <body>
          <div class="header">
            <h1>Cable Technical Datasheet</h1>
            <div>
              <span class="badge">IS 7098 & IS 8130 Compliant</span>
            </div>
          </div>
          <p><strong>Cable Description:</strong> ${data.cores} Core x ${data.area} sq.mm ${data.conductorName} Cable</p>
          
          <table>
            <tbody>
              <tr><th>Conductor Material</th><td>${data.conductorName}</td></tr>
              <tr><th>Conductor Area</th><td>${data.area} mm²</td></tr>
              <tr><th>Number of Cores</th><td>${data.cores}</td></tr>
              <tr><th>Insulation Thickness</th><td>${data.insulationThk} mm</td></tr>
              <tr><th>Inner Sheath Thickness</th><td>${data.innerSheathThk} mm</td></tr>
              <tr><th>Armour Thickness</th><td>${data.armourThk} mm</td></tr>
              <tr><th>Outer Sheath Thickness</th><td>${data.outerSheathThk} mm</td></tr>
            </tbody>
          </table>

          <h2 style="margin-top: 40px; font-size: 18px;">Calculated Parameters</h2>
          <table>
            <tbody>
              <tr><th>Approx Conductor Diameter</th><td>${data.condDia} mm</td></tr>
              <tr><th>Overall Cable Diameter</th><td>${data.overallDia} mm</td></tr>
              <tr><th>DC Resistance @ 20°C</th><td>${data.r20} Ω/km</td></tr>
              <tr><th>AC Resistance @ 90°C</th><td>${data.r90} Ω/km</td></tr>
              <tr><th>Short Circuit Rating (1s)</th><td>${data.scRating} kA</td></tr>
            </tbody>
          </table>
          
          <div style="margin-top: 50px; font-size: 12px; color: #6b7280; text-align: center;">
            Generated by Parametric Cable Engine
          </div>
        </body>
      </html>
    `;

    await page.setContent(htmlContent, { waitUntil: "networkidle0" });
    
    const pdfBuffer = await page.pdf({
      format: "A4",
      printBackground: true,
      margin: { top: "20px", bottom: "20px", left: "20px", right: "20px" },
    });

    await browser.close();

    return new NextResponse(pdfBuffer, {
      status: 200,
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="Datasheet_${data.cores}Cx${data.area}.pdf"`,
      },
    });
  } catch (error: any) {
    console.error("PDF Generation Error:", error);
    return NextResponse.json({ error: "Failed to generate PDF" }, { status: 500 });
  }
}
